import { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { playAlarmTone } from '@/lib/alarmSounds';

declare global {
  interface Window {
    playMedicationAlarm?: () => boolean;
    webkitAudioContext?: typeof AudioContext;
  }
}

// VAPID public key generated by generate-vapid-keys edge function
const VAPID_PUBLIC_KEY = 'BO8xDxJax6gfkBRkuDxVcP5ORJlUZ72fY-ND6lmA-5gAGZuRnogK27r4csu7eE4K_hTjowuw4z13Cz-4mYyxM80';

export type NotificationPermissionState = 'default' | 'granted' | 'denied' | 'unsupported';

export function usePushNotifications() {
  const { user } = useAuth();
  const [permission, setPermission] = useState<NotificationPermissionState>('default');
  const [subscription, setSubscription] = useState<PushSubscription | null>(null);
  const [isSupported, setIsSupported] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  // Check if push notifications are supported
  useEffect(() => {
    const supported = 'Notification' in window && 'serviceWorker' in navigator && 'PushManager' in window;
    setIsSupported(supported);

    if (supported) {
      setPermission(Notification.permission as NotificationPermissionState);
    } else {
      setPermission('unsupported');
    }
  }, []);

  // Check for existing subscription
  useEffect(() => {
    const checkSubscription = async () => {
      if (!isSupported) return;

      try {
        const registration = await navigator.serviceWorker.ready;
        const existingSubscription = await registration.pushManager?.getSubscription();
        setSubscription(existingSubscription);
      } catch (error) {
        console.error('Error checking push subscription:', error);
      }
    };

    checkSubscription();
  }, [isSupported]);

  // Listen for messages from service worker (e.g., MEDICATION_TAKEN, PLAY_ALARM)
  useEffect(() => {
    if (!('serviceWorker' in navigator)) return;

    const handler = (event: MessageEvent) => {
      if (event.data?.type === 'MEDICATION_TAKEN') {
        window.dispatchEvent(new CustomEvent('sw-medication-taken', {
          detail: {
            medicationId: event.data.medicationId,
            scheduledTime: event.data.scheduledTime,
          },
        }));
      }

      if (event.data?.type === 'PLAY_MEDICATION_ALARM') {
        playAlarmTone();
      }
    };

    navigator.serviceWorker.addEventListener('message', handler);
    return () => navigator.serviceWorker.removeEventListener('message', handler);
  }, []);

  // Request notification permission
  const requestPermission = useCallback(async (): Promise<boolean> => {
    if (!isSupported) {
      console.warn('Push notifications are not supported');
      return false;
    }

    setIsLoading(true);

    try {
      const result = await Notification.requestPermission();
      setPermission(result as NotificationPermissionState);
      return result === 'granted';
    } catch (error) {
      console.error('Error requesting notification permission:', error);
      return false;
    } finally {
      setIsLoading(false);
    }
  }, [isSupported]);

  // Save subscription to database
  const saveSubscriptionToDb = useCallback(async (pushSubscription: PushSubscription) => {
    if (!user) return;

    const p256dh = arrayBufferToBase64(pushSubscription.getKey('p256dh')!);
    const auth = arrayBufferToBase64(pushSubscription.getKey('auth')!);

    const { error } = await supabase
      .from('push_subscriptions')
      .upsert(
        {
          user_id: user.id,
          endpoint: pushSubscription.endpoint,
          p256dh,
          auth,
          updated_at: new Date().toISOString(),
        },
        { onConflict: 'user_id,endpoint' }
      );

    if (error) {
      console.error('Error saving push subscription:', error);
    }
  }, [user]);

  // Remove subscription from database
  const removeSubscriptionFromDb = useCallback(async (endpoint: string) => {
    if (!user) return;

    await supabase
      .from('push_subscriptions')
      .delete()
      .eq('user_id', user.id)
      .eq('endpoint', endpoint);
  }, [user]);

  // Subscribe to push notifications
  const subscribe = useCallback(async (): Promise<boolean> => {
    if (!isSupported || !user) {
      return false;
    }

    setIsLoading(true);

    try {
      if (Notification.permission !== 'granted') {
        const granted = await requestPermission();
        if (!granted) return false;
      }

      const registration = await navigator.serviceWorker.ready;

      const pushSubscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY) as BufferSource,
      });

      setSubscription(pushSubscription);

      await saveSubscriptionToDb(pushSubscription);

      return true;
    } catch (error) {
      console.error('Error subscribing to push notifications:', error);
      return false;
    } finally {
      setIsLoading(false);
    }
  }, [isSupported, user, requestPermission, saveSubscriptionToDb]);

  // Unsubscribe from push notifications
  const unsubscribe = useCallback(async (): Promise<boolean> => {
    if (!subscription) return true;

    setIsLoading(true);

    try {
      const endpoint = subscription.endpoint;
      await subscription.unsubscribe();
      setSubscription(null);

      await removeSubscriptionFromDb(endpoint);

      return true;
    } catch (error) {
      console.error('Error unsubscribing from push notifications:', error);
      return false;
    } finally {
      setIsLoading(false);
    }
  }, [subscription, removeSubscriptionFromDb]);

  // Send a local notification (for testing or immediate notifications)
  const sendLocalNotification = useCallback(
    async (title: string, options?: NotificationOptions & { playAlarm?: boolean }): Promise<boolean> => {
      if (!isSupported || Notification.permission !== 'granted') {
        return false;
      }

      try {
        // Play alarm sound for medication notifications
        if (options?.playAlarm !== false) {
          playAlarmTone();
        }

        const registration = await navigator.serviceWorker.ready;
        await registration.showNotification(title, {
          icon: '/pwa-192x192.png',
          badge: '/pwa-192x192.png',
          ...options,
        });
        return true;
      } catch (error) {
        console.error('Error sending notification:', error);
        return false;
      }
    },
    [isSupported]
  );

  // Schedule a medication reminder (local fallback)
  const scheduleMedicationReminder = useCallback(
    async (medicationName: string, dosage: string, scheduledTime: Date): Promise<boolean> => {
      const now = new Date();
      const delay = scheduledTime.getTime() - now.getTime();

      const notifOptions = {
        body: `Take ${dosage} of ${medicationName}`,
        tag: `medication-${medicationName}-${scheduledTime.getTime()}`,
        requireInteraction: true,
        playAlarm: true,
      };

      if (delay <= 0) {
        return sendLocalNotification(`Time for ${medicationName}`, notifOptions);
      }

      setTimeout(() => {
        sendLocalNotification(`Time for ${medicationName}`, notifOptions);
      }, delay);

      return true;
    },
    [sendLocalNotification]
  );

  return {
    permission,
    subscription,
    isSupported,
    isLoading,
    isSubscribed: !!subscription,
    requestPermission,
    subscribe,
    unsubscribe,
    sendLocalNotification,
    scheduleMedicationReminder,
  };
}

// Helper functions
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return window.btoa(binary);
}
